name: ebook UI NRT 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

    
run-name: ebooks UI NRT by @${{ github.actor }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Clean and build the project
      run:  mvn clean

    - name: Run tests
      run: mvn test -Dcucumber.options='--tags @NRT'

    - name: Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/reports
