# This is a basic workflow that is manually triggered

name: ebook UI smoke tests On demand

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    
run-name: ebooks UI Smoke Tests by @${{ github.actor }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run tests
      run: mvn test 
