name: ebook UI Smoke Tests On Demand

on:
  workflow_dispatch:
    inputs:
      run-name:
        description: 'Run name for ebook UI Smoke Tests'
        required: true
        default: 'ebooks UI Smoke Tests by @${{ github.actor }}'

jobs:
  tests-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build the project
      run: mvn clean install

    - name: Run tests
      run: mvn test
